version: 2
jobs:
  build:
    working_directory: ~/hipay/hipay-fullservice-sdk-ios
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      GYM_CODE_SIGNING_IDENTITY: 'iPhone Distribution: HiPay Group (7RLJNKW437)'
      GYM_SCHEME: HiPayFullservice-Example
      GYM_WORKSPACE: Example/HiPayFullservice.xcworkspace
      XCODE_SCHEME: HiPayFullservice-Example
      LANG: en_US.UTF-8
    macos:
      xcode: '9.0'
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          working_directory: ~/hipay/hipay-fullservice-sdk-ios
          command: xcodebuild -version
      - run: cd Example; pod install
      - run: brew update
      - run: brew uninstall xctool && brew install --HEAD xctool
      # This is based on your 1.0 configuration file or project settings
      - run: git lfs pull
      - run: set -o pipefail && xcodebuild clean build test -workspace 'Example/HiPayFullservice.xcworkspace' -scheme 'HiPayFullservice-Example' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= | tee $CIRCLE_ARTIFACTS/xcode_raw.log | xcpretty --color --report junit --output $CIRCLE_TEST_REPORTS/xcode/results.xml
      - run: find $HOME/Library/Developer/Xcode/DerivedData -name '*.xcactivitylog' -exec cp {} $CIRCLE_ARTIFACTS/xcactivitylog \; || true
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
